---
- hosts: 192.168.56.102
  roles:
    - python
    - java
    - role: change-motd
      vars:
        motd: "Ansible Managed node by crregio"
    - role: create-user
      vars:
        username: "stupident1911455"
        name: "Clarissa Regio"
